sudo: true
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install libarmadillo
script: cmake ./ && make